services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7602561602:AAEsPOV_bnNr-54aPiprBkCYYWHN3HXurck
      - key: GROUP_CHAT_ID
        value: -1002738262584
      - key: PORT
        value: 10000
